// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARMiKUjibVUhtLfsmSGMJs5H3jAO52xCM',
    appId: '1:413237222794:web:19def8f79fd0c8f6a9fc73',
    messagingSenderId: '413237222794',
    projectId: 'eatmore-840ac',
    authDomain: 'eatmore-840ac.firebaseapp.com',
    storageBucket: 'eatmore-840ac.appspot.com',
    measurementId: 'G-CLRJ07KLQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1bWgSNoWerv3QyHICHqXw1Du6gGl58Nc',
    appId: '1:413237222794:android:6d3bde007c1353d8a9fc73',
    messagingSenderId: '413237222794',
    projectId: 'eatmore-840ac',
    storageBucket: 'eatmore-840ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK9EUGTtiXvy0iRFl91TK6jCqi54c7gR8',
    appId: '1:413237222794:ios:f511d6ce37581731a9fc73',
    messagingSenderId: '413237222794',
    projectId: 'eatmore-840ac',
    storageBucket: 'eatmore-840ac.appspot.com',
    iosBundleId: 'com.example.eatmore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK9EUGTtiXvy0iRFl91TK6jCqi54c7gR8',
    appId: '1:413237222794:ios:e88051b990a92f77a9fc73',
    messagingSenderId: '413237222794',
    projectId: 'eatmore-840ac',
    storageBucket: 'eatmore-840ac.appspot.com',
    iosBundleId: 'com.example.eatmore.RunnerTests',
  );
}
